server:
  port: 0

spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

management:
  endpoint:
    mappings:
      enabled: true