server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    consul:
      discovery:
        # Making the Consul Instance ID Unique
        # @see: https://cloud.spring.io/spring-cloud-consul/multi/multi_spring-cloud-consul-discovery.html#_making_the_consul_instance_id_unique
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

logging:
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
