---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: config
  namespace: default
spec:
  selector:
    matchLabels:
      app: config
  replicas: 1
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: sangdongvan/piggymetrics-config
          imagePullPolicy: Always
