security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ACCOUNT_SERVICE_PASSWORD
      accessTokenUri: http://auth-service/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      uri: mongodb://user:pwd@localhost:27000/piggymetrics

feign:
  hystrix:
    enabled: true
