server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: info,metrics,health

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service/users/current

spring:
  rabbitmq:
    host: localhost

logging:
  level:
    org.springframework.security: INFO
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
