server:
  port: 0

logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq

management:
  endpoint:
    mappings:
      enabled: true