server:
  port: 0

spring:
  cloud:
    consul:
      discovery:
        # Making the Consul Instance ID Unique
        # @see: https://cloud.spring.io/spring-cloud-consul/multi/multi_spring-cloud-consul-discovery.html#_making_the_consul_instance_id_unique
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  rabbitmq:
    host: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:18001/uaa/users/current

logging:
  level:
    org.springframework.security: INFO
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
