security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      uri: mongodb://user:pwd@localhost:27000/piggymetrics

server:
  servlet:
    context-path: /statistics

rates:
  url: https://api.exchangeratesapi.io
