security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: STATISTICS_SERVICE_PASSWORD
      accessTokenUri: http://localhost:18001/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      uri: mongodb://user:pwd@localhost:27000/piggymetrics

rates:
  url: https://api.exchangeratesapi.io
